### ISSUE TITLE
Speed difference 

### ISSUE THREAD

**Issue by sahara101** [openspeedtest/Docker-Image#14]
Hello, 

using container I am getting these LAN speeds to my laptop:

https port is 4568 external, 3001 docker. 

from hostname behind nginx proxy manager configured with ketsencryp on npm side:

160 Mbps download
399 Mbps upload

from ip:port https:

297 Mbps download
419 Mbps upload

from speediest.net from laptop:

522 Mbps download
415 Mbps upload

I understand that from speedtest.net I am testing internet speed, but still this seems wrong. openspeedtest seems to give me slow speeds, also big difference between direct ip and behind proxy.

Here my container:

version: '3.3'
services:
    speedtest:
       environment:

DISABLED           - ENABLE_LETSENCRYPT=True
DISABLED           - DOMAIN_NAME=DOMAIN
DISABLED           - USER_EMAIL=EMAIL
DISABLED           - VERIFY_OWNERSHIP="TXT-FILE-CONTENT"
            - PUID=1027
            - PGID=100
            - TZ=Europe/Bucharest
       volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/volume1/docker/speedtest/open:/config'
       restart: unless-stopped
       container_name: openspeedtest
       ports:
DISABLED            - '4567:3000'
            - '4568:3001'
       image: openspeedtest/latest

Thanks!

**Comment by openspeedtest** [comment]
Check your server's CPU and disk usage. If you are using NPM or any other proxy server, use the HTTP port of OpenSpeedTest. Also, check without the reverse proxy enabled. Let me know the results. It might be an issue with server performance or reverse proxy configuration.

**Comment by sahara101** [comment]
Thanks I have done this and disabled some npm settings. Seems better. I will make several tests.
