### ISSUE TITLE
Unable to see client IPs using a reverse proxy

### ISSUE THREAD

**Issue by bobbyl140** [openspeedtest/Docker-Image#19]
I have the Docker container behind my Apache proxy, which can successfully pass clients' real IPs to other backend services using some combination of `X-Forwarded-For` and `X-Real-IP`. But when I take a speedtest, the IP is listed as `(null)` and the same shows up in the response body in my browser console. 

As a solution, if it's not implemented, please implement this (these) header(s), or if it is, please help me configure Apache (and maybe also add a sample Apache config :) )

**Comment by openspeedtest** [comment]
@bobbyl140 Can you post a screenshot? Docker image shows IP Address 🤔

**Comment by bobbyl140** [comment]
I have in my Apache config:
```
ProxyPreserveHost On
RequestHeader always set X-Real-IP "%{HTTP:X-Forwarded-For}e"
RequestHeader always set X-Forwarded-For "%{HTTP:X-Forwarded-For}e"
```
(This works for all other services)

The browser shows:
<img width="660" alt="Screenshot 2024-02-13 at 11 21 32 PM" src="https://github.com/openspeedtest/Docker-Image/assets/61990607/47ef42b8-1a36-42e6-9e51-0e35e0bc4ca8">
(Note the speedtest does indeed work)

**Comment by openspeedtest** [comment]
This is not OpenSpeedTest. 😁
