### ISSUE TITLE
Wrong results in download and upload

### ISSUE THREAD

**Issue by jimbo27** [openspeedtest/Docker-Image#5]
I tried the docker image openspeedtest/latest:latest.
I got wrong test results using Chrome browser:
![image](https://user-images.githubusercontent.com/5084469/227532335-f688ef91-1339-4ca9-990e-fc08aa6679b3.png)

Download should be 100 Mbit and upload 10 Mbit as shown here made by another speedtest Docker tool:
![image](https://user-images.githubusercontent.com/5084469/227533045-bde7cc64-4f90-43a8-86a6-fd73fad53b33.png)

**Comment by jimbo27** [comment]
It looks like I measured my local network WLAN speed.
I guess I didn't use the tool correctly then.

It is unclear to me how to measure the speed to the outside (WAN).

**Comment by openspeedtest** [comment]
You conducted a speed test between your server and client, which indicates the LAN speed and not the internet speed.
